---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  markdownlint:
    enabled: true
  pep8:
    enabled: true

exclude_paths:
- tests/
- .idea/

ratings:
  paths:
  - "**.py"
