build:
  image: python:3.4-alpine
  commands:
    - pip install -r requirements/development.txt
    - PYTHONPATH=src py.test --cov=src --verbose --color=yes tests

compose:
  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v2.2.1
    ports: [ "4001:4001" ]
    command: >
      --listen-client-urls 'http://etcd:4001'
      --advertise-client-urls 'http://etcd:4001'
      --initial-cluster-state new