doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - flask
autodetect: yes
requirements:
    - requirements/development.txt
ignore-paths:
    - docs
    - sample
ignore-patterns:
    - .*__init__.py
python-targets:
    - 3