version: '2'
services:
  cobalt1:
    image: presslabs/cobalt:latest
    expose:
      - "80"
    volumes:
      - ./sample/config1:/etc/cobalt
      - ./../mnt/root1:/mnt
    depends_on:
      - etcd
    links:
      - etcd
  cobalt2:
    image: presslabs/cobalt:latest
    expose:
      - "80"
    volumes:
      - ./sample/config2:/etc/cobalt
      - ./../mnt/root2:/mnt
    depends_on:
      - etcd
    links:
      - etcd
  cobalt3:
    image: presslabs/cobalt:latest
    expose:
      - "80"
    volumes:
      - ./sample/config3:/etc/cobalt
      - ./../mnt/root3:/mnt
    depends_on:
      - etcd
    links:
      - etcd
  ha:
    image: haproxy:1.6.5-alpine
    depends_on:
        - cobalt1
        - cobalt2
        - cobalt3
    links:
        - cobalt1:cobalt1
        - cobalt2:cobalt2
        - cobalt3:cobalt3
    ports:
        - "80:80"
    volumes:
        - ./sample/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v2.2.1
    ports: [ "4001:4001" ]
    command: >
      --listen-client-urls 'http://etcd:4001'
      --advertise-client-urls 'http://etcd:4001'
      --initial-cluster-state new
